import type { CSSProperties } from "react";
import dotData from "./creation-dots.json";

/**
 * The two reaching arms from Michelangelo's Creation of Adam, drawn as ~3,800
 * individual <circle> elements from data generated by
 * scripts/generate-creation-dots.ps1.
 *
 * Every dot is a real element so it can be animated. Dots are bucketed into
 * layers by horizontal position, and each layer carries its own drift vector,
 * so on scroll the field parts outward and fades — the image dissipating rather
 * than sliding away. Bucketing (rather than one animation per circle) keeps the
 * animation count at 24 instead of 3,800, which is the difference between a
 * composited effect and a stalled main thread.
 *
 * The whole effect is CSS-only (scroll-driven timeline), gated behind @supports
 * and prefers-reduced-motion in globals.css, so unsupported browsers simply get
 * the static plate.
 */

const { cols, rows, dots } = dotData;

/**
 * One layer per column. Each column slides straight up and fades at its own
 * rate, so the plate comes apart as a vertical comb rather than as one block —
 * which is why the grid is kept coarse: at this density the columns are distinct
 * enough for the staggered slide to read.
 *
 * Rates follow two out-of-phase sine waves across the columns rather than random
 * values, so neighbouring columns differ but the field still empties in a
 * travelling ripple instead of a jumble. A small hash term keeps adjacent
 * columns from ever moving in lockstep.
 *
 * All deterministic, so server and client render identical markup.
 */
function driftFor(column: number) {
  const wave = 0.5 + 0.5 * Math.sin(column * 0.34);
  const jitter = ((column * 7) % 5) * 1.6;
  // Far enough to carry a column off the top of the panel, not merely off the
  // top of the plate — the plate sits below the heading, so a column starting at
  // its bottom edge has the plate's own height plus the heading block to clear.
  const rise = 62 + wave * 20 + jitter;
  // How much progress a column takes to fade out. The spread is kept narrow — a
  // wide spread left some columns fully gone while their neighbours were
  // untouched, which read as isolated blocks rather than a dissolving image.
  const span = 0.62 + (0.5 + 0.5 * Math.sin(column * 0.21 + 1.1)) * 0.2;
  return {
    dy: +(-rise).toFixed(1),
    span: +span.toFixed(3),
  };
}

type Layer = { column: number; dy: number; span: number; dots: number[][] };

const layers: Layer[] = (() => {
  const byColumn = new Map<number, Layer>();
  for (const dot of dots) {
    const [x] = dot;
    let layer = byColumn.get(x);
    if (!layer) {
      const { dy, span } = driftFor(x);
      layer = { column: x, dy, span, dots: [] };
      byColumn.set(x, layer);
    }
    layer.dots.push(dot);
  }
  return [...byColumn.values()].sort((a, b) => a.column - b.column);
})();

type Props = {
  className?: string;
};

export function CreationDotField({ className = "" }: Props) {
  return (
    <svg
      viewBox={`0 0 ${cols} ${rows}`}
      // `slice` keeps the field bleeding off both edges at every viewport size
      // instead of letterboxing into a small band on narrow screens.
      preserveAspectRatio="xMidYMid slice"
      className={className}
      // currentColor rather than a variable: var() is not resolved inside SVG
      // presentation attributes, and the field wants the page's ink anyway.
      fill="currentColor"
      // SVG clips to its viewBox by default, which would cut the rising columns
      // off at the top of the plate. Letting them overflow lets them travel all
      // the way up the panel; the pinned stage clips them at the viewport edge.
      style={{ overflow: "visible" }}
      role="img"
      aria-label="Michelangelo's Creation of Adam — the hands of God and Adam reaching toward one another — drawn as a field of dots"
    >
      {layers.map((layer) => (
        <g
          key={layer.column}
          className="v3-dot-layer"
          style={
            {
              "--dy": `${layer.dy}px`,
              "--span": layer.span,
            } as CSSProperties
          }
        >
          {layer.dots.map(([x, y, r]) => (
            <circle key={`${x}-${y}`} cx={x + 0.5} cy={y + 0.5} r={r} />
          ))}
        </g>
      ))}

    </svg>
  );
}
